### ISSUE TITLE
bootstrap failure

### ISSUE THREAD

**Issue by jvanvorst** [LudovicRousseau/PCSC#170] opened 2024-03-21 19:45 UTC
Just cloned, and ./bootstrap failed.  I think I have all the build tools installed.  Running ubuntu 22.04.
master branch.

jim@Jim-Home:PCSC (master)$ git info
https://salsa.debian.org/rousseau/PCSC.git

jim@Jim-Home:PCSC (master)$ ./bootstrap 
+ test -f Makefile
+ rm -rf autom4te.cache aclocal.m4 config.guess config.log config.status config.sub depcomp ltmain.sh
+ autoreconf --verbose --install
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf
configure.ac:30: error: possibly undefined macro: AS_IF
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:40: error: possibly undefined macro: AC_MSG_WARN
configure.ac:52: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:110: error: possibly undefined macro: AC_MSG_RESULT
configure.ac:233: error: possibly undefined macro: AC_CHECK_PROG
autoreconf: error: /usr/bin/autoconf failed with exit status: 1

jim@Jim-Home:PCSC (master)$ autoconf --version
autoconf (GNU Autoconf) 2.71
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>, <https://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

jim@Jim-Home:PCSC (master)$ autoreconf --version
autoreconf (GNU Autoconf) 2.71
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>, <https://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

jim@Jim-Home:PCSC (master)$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
jim@Jim-Home:PCSC (master)$ 
jim@Jim-Home:PCSC (master)$ 
jim@Jim-Home:PCSC (master)$ 
jim@Jim-Home:PCSC (master)$ which flex
/usr/bin/flex
jim@Jim-Home:PCSC (master)$

**Comment by LudovicRousseau** [comment] 2024-03-21 20:01
have you installed [autoconf-archive](https://savannah.gnu.org/projects/autoconf-archive/) as documented?
https://pcsclite.apdu.fr/#dependencies

**Comment by LudovicRousseau** [comment] 2024-04-01 15:34
I guess the problem is fixed now.

**Closed by LudovicRousseau** 2024-04-01 15:34 UTC
