### ISSUE TITLE
Reader disconnects are noisy in journal/logs

### ISSUE THREAD

**Issue by Jakuje** [LudovicRousseau/PCSC#110] opened 2021-10-06 16:38 UTC
### Versions

* smart card reader driver name and version: pcsc-lite-ccid-1.4.34-1.fc34.x86_64
* pcsc-lite version: 1.9.1-1.fc34
* the output of the command `/usr/sbin/pcscd --version`:
```
pcsc-lite version 1.9.1.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2018 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.infradead.org>.
Enabled features: Linux x86_64-redhat-linux-gnu libsystemd serial usb libudev usbdropdir=/usr/lib64/pcsc/drivers ipcdir=/run/pcscd filter configdir=/etc/reader.conf.d
```

### Platform

* Operating system or GNU/Linux distribution name and version: Fedora 34
* Smart card middleware name and version: Probably OpenSC
* Smart card reader manufacturer name and reader model name: Alcor Micro AU9540 00 00
* Smart card name: Should not be relevant

### Log
```
oct 06 05:03:29 user pcscd[52231]: 00400073 ccid_usb.c:858:WriteUSB() write failed (3/4): -4 LIBUSB_ERROR_NO_DEVICE
oct 06 05:03:29 user pcscd[52231]: 00000010 ifdwrapper.c:364:IFDStatusICC() Card not transacted: 617
oct 06 05:03:30 user pcscd[52231]: 01000094 eventhandler.c:336:EHStatusHandlerThread() Error communicating to: Alcor Micro AU9540 00 00
oct 06 05:03:30 user pcscd[52231]: 00000056 ccid_usb.c:1343:InterruptRead() libusb_submit_transfer failed: LIBUSB_ERROR_NO_DEVICE
oct 06 05:03:31 user pcscd[52231]: 00400082 ccid_usb.c:858:WriteUSB() write failed (3/4): -4 LIBUSB_ERROR_NO_DEVICE
oct 06 05:03:31 user pcscd[52231]: 00000010 ifdwrapper.c:364:IFDStatusICC() Card not transacted: 617
```

We have the following bug reported that the above logs show repetitively when smart card reader is disconnected. This might be the case for disconnecting a reader, undocking a computer or removing a USB token.

The questions would be:
 * when we got error "Card not transacted", should the pcsc try over?
 * When we got NO_DEVICE error (right, this is from CCID, but I wanted to avoid duplicating error report there too), should not CCID stop until it will get information the (new?) device is ready?
 * If these are expected, should these logs be less verbose than ERRORs?

https://bugzilla.redhat.com/show_bug.cgi?id=2011128

**Comment by LudovicRousseau** [comment] 2021-10-10 15:41
The problem should now be fixed with the git versions of PCSC and CCID.

On the original RedHat bug report I see "Every second 2 messages appear in logs, they keep appearing until the daemon is restarted".
This is a different problem. It looks like pcscd does NOT detect the reader removal and continue trying to talk to the reader.
Can you reproduce this problem?

**Comment by LudovicRousseau** [comment] 2021-10-11 16:35
OK. We will see what Santiago Gala gets with the updated packages.

**Comment by sgala** [comment] 2021-10-14 11:42
I get the same behaviour. Apparently it is not so much a matter of me unplugging the reader, but of me undocking the laptop, when the reader is in the dock. Undocking kills the USB hubs in a bad way (but this is a separate bug).

I will try later both the unplugging of the reader and the undocking with pcscd started in the foreground and logging.

**Comment by LudovicRousseau** [comment] 2021-10-14 12:56
I also think it is a problem with the dock.
Can you run the command `udevadm monitor--property` then dock and undock the laptop.
I guess some events are not seen or reported by libudev.

What laptop and dock do you use?

In your case I would suggest to build pcsc-lite using `--disable-libudev` to use libusb instead of libudev. pcscd will continuously rescan the USB bus and should be able to detect removed readers.
It is not a fix but a way to avoid filling your disk with logs.

**Comment by LudovicRousseau** [comment] 2021-11-07 21:54
@sgala I need you feedback to understand (and possibly fix) the problem.
Please help me and answer to my questions above.

**Comment by sgala** [comment] 2021-11-08 15:10
Sorry, I got overwhelmed with work. The situation is:

* the problem is linked to the dock not handling properly the 2 usb hubs on it when docked/undocked
* possibly it is a BIOS (dock bios or ACPI bios) problem, as I have seen both Windows and Linux behave the same (USB-C hubs are only visible if thunderbolt undock/dock happens while the machine is suspended).
* I unplugged the card reader as it was giving this log spam most of the times I unplugged and I use it rarely, so now I have to plug it when I want to use it and take care of the problem after unplugging it.

I'm running packages that were suggested to fix the problem, but the problem is still there (I got a bit lost with the suggestions so I'm not sure if this is what I'm expected to be running):

```
$ dnf list pcsc-lite pcsc-lite-libs pcsc-lite-ccid pcsc-perl pcsc-tools
Last metadata expiration check: 0:01:17 ago on lun 08 nov 2021 16:05:59.
Installed Packages
pcsc-lite.x86_64                       1.9.4-1.fc34                    @copr:copr.fedorainfracloud.org:jjelen:pcsc-lite-future
pcsc-lite-ccid.x86_64                  1.4.36-1.fc34                   @copr:copr.fedorainfracloud.org:jjelen:pcsc-lite-future
pcsc-lite-libs.x86_64                  1.9.4-1.fc34                    @copr:copr.fedorainfracloud.org:jjelen:pcsc-lite-future
pcsc-perl.x86_64                       1.4.14-16.fc34                  @fedora                                                
pcsc-tools.x86_64                      1.5.7-3.fc34                    @fedora                                                
Available Packages
pcsc-lite.src                          1.9.4-1.fc34                    copr:copr.fedorainfracloud.org:jjelen:pcsc-lite-future 
pcsc-lite-ccid.src                     1.4.36-1.fc34                   copr:copr.fedorainfracloud.org:jjelen:pcsc-lite-future 
pcsc-lite-libs.i686                    1.9.1-1.fc34                    fedora    
```

Tell me specific, concrete actions that are not too time consuming to check the problem and I'll try them.

**Comment by LudovicRousseau** [comment] 2021-11-08 15:58
- What laptop and dock models do you use?

1. connect the smart card reader to the dock
2. start the command `udevadm monitor --property`
3. then dock the laptop
4. and undock the laptop
5. stop the `udevadm` command
5. send me the generated output

**Comment by sgala** [comment] 2021-11-08 17:05
Laptop is a "P1 Gen 3 (type 20TH, 20TJ ) Laptop (ThinkPad) - Type 20TJ " (according to Lenovo)
Dock is tricky, they list scores of models. I think it is a:  https://support.lenovo.com/us/en/solutions/PD500252 ThinkPad Thunderbolt 3 Workstation Dock (230W)
The cable is not exactly the same, but it has both a power and a USB-C connector, which is very characteristic. Labelled as 230W.

I sent the files in a separate comment

**Comment by sgala** [comment] 2021-11-08 17:22
Now, the same process but I: start monitoring, suspend, dock, wakeup, check that usb ports are enumerated, suspend, undock, wakeup, stop monitor -> [monitor-suspending.txt](https://github.com/LudovicRousseau/PCSC/files/7498853/monitor-suspending.txt)

**Comment by sgala** [comment] 2021-11-16 11:02
This [monitor.log](https://github.com/LudovicRousseau/PCSC/files/7545722/monitor.log) trace corresponds to the plugging and unplugging of the reader with the dock already on. This works normally as the hub does not disappear in the middle... :)

**Comment by sgala** [comment] 2021-11-18 09:08
> I guess the reader is a USB-A and you have a USB-A to USB-C adaptor. Exact?

The reader is USB-A, but it is the dock that offers a number of USB-A ports. Not sure how.

And no, when I dock the laptop the usb-c or usb-a ports are invisible (hubs 3 and 4 are not there, neither anything in them, in lsubs --tree) until I authorise the dock AND THEN suspend and wake up again. If I set up the BIOS for automated auth of thunderbolt, I still need to unplug AND plug while suspended for the USB-C ports to be seen.

I only see in dmesg the "undocked" ACPI event appear, no matter if I dock or undock, I'm thinking about a bug in acpi bios, module or kernel.

**Comment by LudovicRousseau** [comment] 2021-11-18 12:44
I contacted Lenovo and they said they were working on a similar problem reported by RedHat. I guess that is this issue.

As I already proposed in a previous message:

> In your case I would suggest to `./configure` pcsc-lite using `--disable-libudev` to use libusb instead of libudev. pcscd will continuously rescan the USB bus and should be able to detect removed readers.
> It is not a fix but a way to avoid filling your disk with logs.

This will not fix the problem with the dock but pcscd should detect when the reader is "removed".

**Comment by sgala** [comment] 2021-11-26 15:36
As I don't use often the reader I opted by disconnecting it from the dock. Now I will connect the reader and disconnect it either to laptop or to dock, but disconnecting the reader with the dock connected I don't have the problem with the log spam and battery drain

**Comment by LudovicRousseau** [comment] 2021-11-26 16:18
Thanks for the feedback @sgala.
As I think your issue is related to the dock itself (or the laptop firmware) I can't fix it in PCSC.
I close this issue.

**Closed by LudovicRousseau** 2021-11-26 16:18 UTC
Labels: help wanted

**Comment by sgala** [comment] 2021-11-26 17:46
Thank you for your effort and sorry for the noise, when I started the bug I had not a clear idea about how broken is either the laptop firmware or the dock firmware. I'm leaning towards a laptop firmware / acpi problem.
